"""Generate src/01_text_catalog.js from the spec's catalog tables (§9 and §14).

The spec is the source of truth for every user-visible generated string.
Re-run after editing the spec:  python FieldDrive/gen_catalog.py
"""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs/superpowers/specs/2026-09-23-fielddrive-supervisor-vsr-design.md"
OUT = Path(__file__).parent / "src/01_text_catalog.js"
ID = re.compile(r"^[A-Z]{1,2}_[A-Z0-9_]+$")


def cells(line):
    return [c.strip() for c in line.strip().strip("|").split("|")]


def main():
    text = SPEC.read_text(encoding="utf-8")
    body = text[text.index("## 9. Reason codes"):text.index("## 15. Testing")] + text[text.index("## 17. Revision 2"):]
    cat, header = {}, None
    for line in body.splitlines():
        if not line.startswith("|"):
            header = None
            continue
        row = cells(line)
        if header is None:
            header = row
            continue
        if set(line) <= set("|-: "):
            continue
        col = {h: v for h, v in zip(header, row)}
        rid = col.get("id") or col.get("Code")
        if not rid:
            continue
        if " / " in rid and rid.startswith("O_"):  # O_NEXT / O_DONE / O_SKIP row
            ids = [i.strip() for i in rid.split("/")]
            en = [s.strip() for s in col["EN"].split("·")]
            ar = [s.strip() for s in col["AR"].split("·")]
            for i, e, a in zip(ids, en, ar):
                cat[i] = {"en": e, "ar": a}
            continue
        if not ID.match(rid):
            continue
        if "EN title" in col:  # notifications (body) and follow-ups (context)
            second = "_B" if "EN body" in col else "_C"
            cat[rid] = {"en": col["EN title"], "ar": col["AR title"]}
            cat[rid + second] = {"en": col.get("EN body") or col["EN context"], "ar": col.get("AR body") or col["AR context"]}
        elif "Title EN" in col:  # coaching tips
            cat[rid + "_T"] = {"en": col["Title EN"], "ar": col["Title AR"]}
            cat[rid] = {"en": col["Tip EN"], "ar": col["Tip AR"]}
        else:
            en, ar = col["EN"], col["AR"]
            if rid == "R_COMPETITOR":  # brand choice is a second tap, not part of the label
                en, ar = en.split("→")[0].strip(), ar.split("←")[0].strip()
            cat[rid] = {"en": en, "ar": ar}
    js = "(function () {\n  // GENERATED by gen_catalog.py from the spec. Do not edit by hand.\n  const FD = globalThis.FD;\n  FD.CATALOG = Object.assign(FD.CATALOG || {}, "
    js += json.dumps(cat, ensure_ascii=False, indent=1) + ");\n})();\n"
    OUT.write_text(js, encoding="utf-8")
    print(f"wrote {OUT.name}: {len(cat)} entries")


if __name__ == "__main__":
    main()
