(function () {
  // GENERATED by gen_catalog.py from the spec. Do not edit by hand.
  const FD = globalThis.FD;
  FD.CATALOG = Object.assign(FD.CATALOG || {}, {
 "R_BUYER_ABSENT": {
  "en": "Buyer not available",
  "ar": "صاحب القرار غير موجود"
 },
 "R_BUYER_NO": {
  "en": "Buyer said no",
  "ar": "رفض المشتري"
 },
 "R_ENOUGH": {
  "en": "Already has enough stock",
  "ar": "لديه مخزون كافٍ"
 },
 "R_NO_SHELF": {
  "en": "No shelf space",
  "ar": "لا توجد مساحة على الرف"
 },
 "R_PRICE": {
  "en": "Price or margin concern",
  "ar": "اعتراض على السعر أو الهامش"
 },
 "R_CREDIT": {
  "en": "Credit or payment issue",
  "ar": "مشكلة ائتمان أو سداد"
 },
 "R_COMPETITOR": {
  "en": "Competitor deal",
  "ar": "عرض من منافس"
 },
 "R_NOT_ON_VAN": {
  "en": "Not on the van",
  "ar": "غير متوفر في السيارة"
 },
 "R_SYSTEM": {
  "en": "System or device issue",
  "ar": "مشكلة في النظام أو الجهاز"
 },
 "R_OTHER": {
  "en": "Other (comment required)",
  "ar": "سبب آخر (التعليق مطلوب)"
 },
 "L_APP": {
  "en": "FieldDrive",
  "ar": "فيلد درايف"
 },
 "L_ROLE_SUP": {
  "en": "Supervisor",
  "ar": "المشرف"
 },
 "L_ROLE_VSR": {
  "en": "Salesman",
  "ar": "المندوب"
 },
 "L_OPEN_AS": {
  "en": "Open as",
  "ar": "الدخول باسم"
 },
 "L_NAV_HOME": {
  "en": "Home",
  "ar": "الرئيسية"
 },
 "L_NAV_TEAM": {
  "en": "Team",
  "ar": "الفريق"
 },
 "L_NAV_STORES": {
  "en": "Stores",
  "ar": "المحلات"
 },
 "L_NAV_SKUS": {
  "en": "Products",
  "ar": "المنتجات"
 },
 "L_NAV_OPPS": {
  "en": "Opportunities",
  "ar": "الفرص"
 },
 "L_NAV_LEARN": {
  "en": "Engine learning",
  "ar": "تعلّم النظام"
 },
 "L_NAV_RULES": {
  "en": "Rules",
  "ar": "القواعد"
 },
 "L_TAB_TODAY": {
  "en": "Today",
  "ar": "اليوم"
 },
 "L_TAB_STORE": {
  "en": "Store",
  "ar": "المحل"
 },
 "L_TAB_TODO": {
  "en": "To-do",
  "ar": "المطلوب مني"
 },
 "L_TAB_ME": {
  "en": "Me",
  "ar": "حسابي"
 },
 "L_FOLLOWUPS": {
  "en": "Follow-ups",
  "ar": "المتابعات"
 },
 "L_KPI_NET": {
  "en": "Net sales",
  "ar": "صافي المبيعات"
 },
 "L_KPI_VS_BASE": {
  "en": "vs before pilot",
  "ar": "مقارنة بما قبل التجربة"
 },
 "L_KPI_CONV": {
  "en": "Upsell conversion",
  "ar": "نسبة نجاح البيع الإضافي"
 },
 "L_KPI_UPVAL": {
  "en": "Upsell value",
  "ar": "قيمة البيع الإضافي"
 },
 "L_KPI_REASONS": {
  "en": "Reasons pending",
  "ar": "أسباب معلّقة"
 },
 "L_KPI_ATTN": {
  "en": "Stores needing attention",
  "ar": "محلات تحتاج متابعة"
 },
 "L_P_TEAM": {
  "en": "Team ranking",
  "ar": "ترتيب الفريق"
 },
 "L_P_WHY": {
  "en": "Why it didn't sell",
  "ar": "لماذا لم يُبَع"
 },
 "L_P_OPPS": {
  "en": "Top opportunities",
  "ar": "أهم الفرص"
 },
 "L_P_SKU": {
  "en": "Product performance",
  "ar": "أداء المنتجات"
 },
 "L_P_STORES": {
  "en": "Stores needing attention",
  "ar": "محلات تحتاج متابعة"
 },
 "L_P_INSIGHTS": {
  "en": "What sells where",
  "ar": "ماذا يُباع وأين"
 },
 "L_MORNING": {
  "en": "Today's recommendations",
  "ar": "توصيات اليوم"
 },
 "L_PROMOS_TODAY": {
  "en": "Promos today",
  "ar": "عروض اليوم"
 },
 "L_VAN_CHECK": {
  "en": "Van check",
  "ar": "فحص حمولة السيارة"
 },
 "L_STOPS": {
  "en": "Stops",
  "ar": "الزيارات"
 },
 "L_CONFIRM_LIST": {
  "en": "Confirm list",
  "ar": "تأكيد القائمة"
 },
 "L_OPEN_SB": {
  "en": "Open SalesBuzz",
  "ar": "فتح SalesBuzz"
 },
 "L_NAVIGATE": {
  "en": "Navigate",
  "ar": "الاتجاهات"
 },
 "L_TELL_WHY": {
  "en": "Tell us why",
  "ar": "وضّح السبب"
 },
 "L_DIDNT_OFFER": {
  "en": "Didn't offer",
  "ar": "لم أعرضه"
 },
 "L_ADD_COMMENT": {
  "en": "Add comment",
  "ar": "أضف تعليقاً"
 },
 "L_ADD_PHOTO": {
  "en": "Add shelf photo",
  "ar": "أضف صورة للرف"
 },
 "L_SAVE": {
  "en": "Save",
  "ar": "حفظ"
 },
 "L_CANCEL": {
  "en": "Cancel",
  "ar": "إلغاء"
 },
 "L_BLOCK": {
  "en": "Block",
  "ar": "إيقاف"
 },
 "L_PIN": {
  "en": "Pin",
  "ar": "تثبيت"
 },
 "L_EXEMPT": {
  "en": "Exempt",
  "ar": "إعفاء"
 },
 "L_REPLY": {
  "en": "Reply",
  "ar": "رد"
 },
 "L_SEND_TIP": {
  "en": "Send coaching tip",
  "ar": "إرسال نصيحة"
 },
 "L_SNOOZE": {
  "en": "Snooze to tomorrow",
  "ar": "تأجيل إلى الغد"
 },
 "L_DISMISS": {
  "en": "Dismiss",
  "ar": "تجاهل"
 },
 "L_VIEW_ALL": {
  "en": "View all ({n})",
  "ar": "عرض الكل ({n})"
 },
 "L_ABS": {
  "en": "Absolute",
  "ar": "الأداء الفعلي"
 },
 "L_IMPROVE": {
  "en": "Improvement",
  "ar": "نسبة التحسّن"
 },
 "L_SIMULATED": {
  "en": "Simulated",
  "ar": "بيانات تجريبية"
 },
 "L_FOOTER": {
  "en": "Simulated data for demonstration · Not live SalesBuzz data",
  "ar": "بيانات تجريبية للعرض · ليست بيانات SalesBuzz مباشرة"
 },
 "L_HEALTH": {
  "en": "Assortment health",
  "ar": "صحة التشكيلة"
 },
 "L_SHELF": {
  "en": "Shelf view",
  "ar": "عرض الرف"
 },
 "L_EST_MARGIN": {
  "en": "Est. store margin",
  "ar": "هامش المحل التقديري"
 },
 "L_MSG_SUP": {
  "en": "Message supervisor",
  "ar": "راسل المشرف"
 },
 "L_MSG_VSR": {
  "en": "Message {vsr}",
  "ar": "راسل {vsr}"
 },
 "L_MESSAGES": {
  "en": "Messages",
  "ar": "الرسائل"
 },
 "L_THREADS": {
  "en": "Threads",
  "ar": "المحادثات"
 },
 "B_LAPSED": {
  "en": "Last ordered {days} days ago. Used to take {qty} {unit} a visit.",
  "ar": "آخر طلب قبل {days} يوماً. كان يأخذ {qty} {unit} في كل زيارة."
 },
 "B_GAP_TAG": {
  "en": "{pct}% of stores {tag} carry this. This store doesn't.",
  "ar": "{pct}٪ من المحلات {tag} توفّر هذا المنتج، وهذا المحل لا يوفّره."
 },
 "B_GAP_LABEL": {
  "en": "{pct}% of {label} stores carry this. This store doesn't.",
  "ar": "{pct}٪ من محلات فئة {label} توفّر هذا المنتج، وهذا المحل لا يوفّره."
 },
 "B_GAP_MUST": {
  "en": "On the must-stock list for {label} stores. Not on this shelf yet.",
  "ar": "ضمن قائمة المنتجات الأساسية لمحلات {label}، وغير موجود على الرف بعد."
 },
 "B_UP_PACK": {
  "en": "Sells {sku_small} steadily. Offer the {sku} box for more cash per visit.",
  "ar": "يبيع {sku_small} بانتظام. اعرض علبة {sku} لربح أكبر في كل زيارة."
 },
 "B_UP_FLAVOUR": {
  "en": "{sku_have} sells well here. Add {sku} to complete the range.",
  "ar": "{sku_have} يُباع جيداً هنا. أضف {sku} لإكمال التشكيلة."
 },
 "B_PROMO": {
  "en": "{promo} until {date}. Good time to stock up.",
  "ar": "{promo} حتى {date}. وقت مناسب لزيادة المخزون."
 },
 "B_PINNED": {
  "en": "Priority from your supervisor.",
  "ar": "أولوية من المشرف."
 },
 "C_PITCH": {
  "en": "Costs {cost} SAR · sells for {rev} SAR · store earns {earn} SAR",
  "ar": "التكلفة {cost} ريال · يُباع بـ {rev} ريال · ربح المحل {earn} ريال"
 },
 "C_PITCH_PC": {
  "en": "Sell at {price} SAR a piece. {pcs} pieces a {unit}",
  "ar": "يُباع بسعر {price} ريال للقطعة، {pcs} قطعة في كل {unit}"
 },
 "C_PITCH_PROMO": {
  "en": "With the promo, store earns {earn} SAR",
  "ar": "مع العرض، ربح المحل {earn} ريال"
 },
 "C_QTY": {
  "en": "Suggested: {qty} {unit} ({pcs} pcs)",
  "ar": "الكمية المقترحة: {qty} {unit} ({pcs} قطعة)"
 },
 "C_FIRST_FILL": {
  "en": "First order. Start with one {unit}",
  "ar": "أول طلب، ابدأ بـ {unit} واحدة"
 },
 "D_ON_VAN": {
  "en": "On van: {qty} {unit}",
  "ar": "في السيارة: {qty} {unit}"
 },
 "D_NOT_VERIFIED": {
  "en": "Van stock not verified",
  "ar": "مخزون السيارة غير مؤكد"
 },
 "D_NOT_ON_VAN": {
  "en": "Not on van today",
  "ar": "غير متوفر في السيارة اليوم"
 },
 "D_DATA_AGE": {
  "en": "Store data from SalesBuzz · {date} {time}",
  "ar": "بيانات المحل من SalesBuzz · {date} {time}"
 },
 "D_EXPIRES": {
  "en": "Valid until end of this visit",
  "ar": "صالحة حتى نهاية هذه الزيارة"
 },
 "D_TIP": {
  "en": "Tip from {sup}: {tip}",
  "ar": "نصيحة من {sup}: {tip}"
 },
 "D_COVER": {
  "en": "Covering for {vsr} today",
  "ar": "تغطية عن {vsr} اليوم"
 },
 "E_WAITING": {
  "en": "Waiting for SalesBuzz order…",
  "ar": "بانتظار طلب SalesBuzz…"
 },
 "E_FULL": {
  "en": "Sold in full",
  "ar": "بيع بالكامل"
 },
 "E_PARTIAL": {
  "en": "Sold partly ({got} of {qty} {unit})",
  "ar": "بيع جزئياً ({got} من {qty} {unit})"
 },
 "E_ALT": {
  "en": "Sold alternative ({alt})",
  "ar": "بيع بديل ({alt})"
 },
 "E_NOT_SOLD": {
  "en": "Not sold",
  "ar": "لم يُبَع"
 },
 "E_NOT_OFFERED": {
  "en": "Not offered",
  "ar": "لم يُعرض"
 },
 "E_PENDING": {
  "en": "Pending. {days} days left to confirm",
  "ar": "قيد التأكيد، متبقٍ {days} يوماً"
 },
 "E_SUSTAINED": {
  "en": "Sustained. Reordered",
  "ar": "مستمر، تم إعادة الطلب"
 },
 "E_RETURNED": {
  "en": "Returned",
  "ar": "مُرتجع"
 },
 "E_EXEMPTED": {
  "en": "Exempted",
  "ar": "معفى"
 },
 "E_NO_REASON": {
  "en": "No reason given",
  "ar": "لا يوجد سبب"
 },
 "E_CORRECTED": {
  "en": "Corrected after SalesBuzz edit",
  "ar": "صُحّح بعد تعديل في SalesBuzz"
 },
 "E_BLOCKED": {
  "en": "Blocked by supervisor",
  "ar": "أوقفه المشرف"
 },
 "E_GATED": {
  "en": "Not eligible: {gate}",
  "ar": "غير مؤهل: {gate}"
 },
 "E_NO_ORDER": {
  "en": "No order found in SalesBuzz",
  "ar": "لم يُعثر على طلب في SalesBuzz"
 },
 "N_ARRIVE": {
  "en": "At {store}",
  "ar": "في {store}"
 },
 "N_ARRIVE_B": {
  "en": "{n} to offer: {sku_list}",
  "ar": "{n} للعرض: {sku_list}"
 },
 "N_ARRIVE_ONE": {
  "en": "At {store}",
  "ar": "في {store}"
 },
 "N_ARRIVE_ONE_B": {
  "en": "This store doesn't carry {sku}. Recommend {qty} {unit}",
  "ar": "هذا المحل لا يوفّر {sku}، اقترح {qty} {unit}"
 },
 "N_SOLD": {
  "en": "Upsell counted",
  "ar": "تم احتساب البيع الإضافي"
 },
 "N_SOLD_B": {
  "en": "{sku} is in the {store} order",
  "ar": "{sku} ضمن طلب {store}"
 },
 "N_NOT_SOLD": {
  "en": "{sku} not in order",
  "ar": "{sku} ليس في الطلب"
 },
 "N_NOT_SOLD_B": {
  "en": "Tap to tell us why. Takes 5 seconds",
  "ar": "اضغط لتوضيح السبب، ٥ ثوانٍ فقط"
 },
 "N_EOD": {
  "en": "{n} reasons still missing",
  "ar": "{n} أسباب ما زالت ناقصة"
 },
 "N_EOD_B": {
  "en": "Add them before you finish the day",
  "ar": "أضفها قبل إنهاء اليوم"
 },
 "N_REPLY": {
  "en": "{sup} replied",
  "ar": "رد {sup}"
 },
 "N_REPLY_B": {
  "en": "About {sku} at {store}",
  "ar": "بخصوص {sku} في {store}"
 },
 "N_REPLY_STORE": {
  "en": "{sup} wrote",
  "ar": "كتب {sup}"
 },
 "N_REPLY_STORE_B": {
  "en": "About {store}",
  "ar": "بخصوص {store}"
 },
 "N_TIP": {
  "en": "New tip from {sup}",
  "ar": "نصيحة جديدة من {sup}"
 },
 "N_TIP_B": {
  "en": "{tip_title}",
  "ar": "{tip_title}"
 },
 "N_REMOVED": {
  "en": "Recommendation removed",
  "ar": "تمت إزالة توصية"
 },
 "N_REMOVED_B": {
  "en": "{sku} at {store} was removed by your supervisor",
  "ar": "أزال المشرف {sku} في {store}"
 },
 "T_REASON": {
  "en": "Why didn't {sku} sell at {store}?",
  "ar": "لماذا لم يُبَع {sku} في {store}؟"
 },
 "T_TIP": {
  "en": "Read tip: {tip_title}",
  "ar": "اقرأ النصيحة: {tip_title}"
 },
 "T_REPLY": {
  "en": "{sup} replied about {sku}",
  "ar": "رد {sup} بخصوص {sku}"
 },
 "T_REPLY_STORE": {
  "en": "{sup} wrote about {store}",
  "ar": "كتب {sup} بخصوص {store}"
 },
 "T_CORRECTION": {
  "en": "Your correction for {store} was {status}",
  "ar": "تم {status} تصحيحك لمحل {store}"
 },
 "T_REVIEW": {
  "en": "Review today's recommendations",
  "ar": "راجع توصيات اليوم"
 },
 "F_RETURN_UPSELL": {
  "en": "Upsell returned at {store}",
  "ar": "مرتجع بعد بيع إضافي في {store}"
 },
 "F_RETURN_UPSELL_C": {
  "en": "{sku} · {qty} {unit} · {vsr}",
  "ar": "{sku} · {qty} {unit} · {vsr}"
 },
 "F_MISSING_REASONS": {
  "en": "{n} reasons missing from {vsr}",
  "ar": "{n} أسباب ناقصة من {vsr}"
 },
 "F_MISSING_REASONS_C": {
  "en": "Oldest from {date}",
  "ar": "أقدمها بتاريخ {date}"
 },
 "F_REPEAT_DECLINE": {
  "en": "{sku} declined {n}× for \"{reason}\"",
  "ar": "رُفض {sku} {n} مرات بسبب \"{reason}\""
 },
 "F_REPEAT_DECLINE_C": {
  "en": "Mostly {vsr} · this week",
  "ar": "غالباً {vsr} · هذا الأسبوع"
 },
 "F_COMPETITOR": {
  "en": "{brand} deals are blocking sales",
  "ar": "عروض {brand} تعيق البيع"
 },
 "F_COMPETITOR_C": {
  "en": "{n} stores · mostly {sku}",
  "ar": "{n} محلات · غالباً {sku}"
 },
 "F_GAP_CLUSTER": {
  "en": "{n} stores {tag} don't carry {sku}",
  "ar": "{n} محلات {tag} لا توفّر {sku}"
 },
 "F_GAP_CLUSTER_C": {
  "en": "Peers with this tag: {pct}% carry it",
  "ar": "{pct}٪ من المحلات المشابهة توفّره"
 },
 "F_VSR_BELOW": {
  "en": "{vsr} is below their usual level",
  "ar": "{vsr} أقل من مستواه المعتاد"
 },
 "F_VSR_BELOW_C": {
  "en": "{pct}% under own baseline · 2 weeks",
  "ar": "أقل بـ {pct}٪ من مستواه · أسبوعان"
 },
 "F_NOT_OFFERED": {
  "en": "{vsr} skips many recommendations",
  "ar": "{vsr} يتجاوز كثيراً من التوصيات"
 },
 "F_NOT_OFFERED_C": {
  "en": "{pct}% not offered this week",
  "ar": "{pct}٪ لم تُعرض هذا الأسبوع"
 },
 "F_CREDIT": {
  "en": "{store} credit is now {status}",
  "ar": "ائتمان {store} أصبح {status}"
 },
 "F_CREDIT_C": {
  "en": "Recommendations paused",
  "ar": "التوصيات متوقفة"
 },
 "F_CORRECTION": {
  "en": "{vsr} suggests a change for {store}",
  "ar": "{vsr} يقترح تعديلاً على {store}"
 },
 "F_CORRECTION_C": {
  "en": "{change}",
  "ar": "{change}"
 },
 "F_VSR_COMMENT": {
  "en": "{vsr} commented on {sku}",
  "ar": "علّق {vsr} على {sku}"
 },
 "F_VSR_COMMENT_C": {
  "en": "{store} · \"{snippet}\"",
  "ar": "{store} · \"{snippet}\""
 },
 "F_VSR_STORE_MSG": {
  "en": "{vsr}: {topic} at {store}",
  "ar": "{vsr}: {topic} في {store}"
 },
 "F_VSR_STORE_MSG_C": {
  "en": "\"{snippet}\"",
  "ar": "\"{snippet}\""
 },
 "F_PHOTO": {
  "en": "New shelf photo from {store}",
  "ar": "صورة رف جديدة من {store}"
 },
 "F_PHOTO_C": {
  "en": "By {vsr} · {date}",
  "ar": "من {vsr} · {date}"
 },
 "F_ENGINE_MISS": {
  "en": "{sku} sells without being recommended",
  "ar": "{sku} يُباع دون توصية"
 },
 "F_ENGINE_MISS_C": {
  "en": "{n} stores · add to rules?",
  "ar": "{n} محلات · إضافته للقواعد؟"
 },
 "F_WATCHLIST": {
  "en": "{sku} returns are high",
  "ar": "مرتجعات {sku} مرتفعة"
 },
 "F_WATCHLIST_C": {
  "en": "{pct}% returned · 28 days",
  "ar": "{pct}٪ مرتجع · ٢٨ يوماً"
 },
 "F_SKIPPED": {
  "en": "{vsr} skipped {n} stops today",
  "ar": "تجاوز {vsr} {n} زيارات اليوم"
 },
 "F_SKIPPED_C": {
  "en": "Most common: {reason}",
  "ar": "الأكثر: {reason}"
 },
 "F_PROMO_LOW": {
  "en": "{promo} ends {date}. Low uptake",
  "ar": "{promo} ينتهي {date}، إقبال ضعيف"
 },
 "F_PROMO_LOW_C": {
  "en": "{pct}% of stores took it",
  "ar": "{pct}٪ من المحلات استفادت"
 },
 "F_COVER": {
  "en": "{vsr2} is covering {vsr} today",
  "ar": "{vsr2} يغطي عن {vsr} اليوم"
 },
 "F_COVER_C": {
  "en": "{route}",
  "ar": "{route}"
 },
 "K_PRICE_T": {
  "en": "Lead with the cash-at-register pitch",
  "ar": "ابدأ بربح المحل النقدي"
 },
 "K_PRICE": {
  "en": "For {sku}: the store pays {cost} SAR and takes {rev} SAR selling singles at {price} SAR. Say the SAR amount, not the percentage.",
  "ar": "لمنتج {sku}: يدفع المحل {cost} ريال ويحصل على {rev} ريال ببيع القطعة بـ {price} ريال. اذكر المبلغ بالريال لا النسبة."
 },
 "K_ENOUGH_T": {
  "en": "Check the shelf before offering",
  "ar": "افحص الرف قبل العرض"
 },
 "K_ENOUGH": {
  "en": "Look at the shelf and backroom first. If stock is old, offer a swap on the next visit instead.",
  "ar": "افحص الرف والمستودع أولاً. إذا كان المخزون قديماً، اعرض الاستبدال في الزيارة القادمة."
 },
 "K_NO_SHELF_T": {
  "en": "Offer a counter caddy",
  "ar": "اقترح علبة عرض على الكاونتر"
 },
 "K_NO_SHELF": {
  "en": "Cake bars and cupcakes come in counter display boxes. Suggest placing one beside the cash drawer.",
  "ar": "الكيك بار والكب كيك تأتي في علب عرض. اقترح وضع واحدة بجانب الكاشير."
 },
 "K_BUYER_NO_T": {
  "en": "Start with one box",
  "ar": "ابدأ بعلبة واحدة"
 },
 "K_BUYER_NO": {
  "en": "Ask for a single box as a trial. If it sells, the next order is easier.",
  "ar": "اطلب علبة واحدة للتجربة. إذا بيعت، يصبح الطلب التالي أسهل."
 },
 "K_COMPETITOR_T": {
  "en": "Answer the {brand} offer",
  "ar": "الرد على عرض {brand}"
 },
 "K_COMPETITOR": {
  "en": "Compare on cash per box: {sku} earns the store {earn} SAR. Mention our current promo if one applies.",
  "ar": "قارن بالربح لكل علبة: {sku} يحقق للمحل {earn} ريال. اذكر عرضنا الحالي إن وُجد."
 },
 "K_BUYER_ABSENT_T": {
  "en": "Visit {store} when the buyer is in",
  "ar": "زر {store} بوجود المشتري"
 },
 "K_BUYER_ABSENT": {
  "en": "The buyer has been away {n} times. Ask the staff for the best time and note it.",
  "ar": "المشتري لم يكن موجوداً {n} مرات. اسأل العاملين عن الوقت المناسب وسجّله."
 },
 "K_NOT_OFFERED_T": {
  "en": "Offer every recommendation once",
  "ar": "اعرض كل توصية مرة واحدة"
 },
 "K_NOT_OFFERED": {
  "en": "Each recommendation is checked for stock and fit. Offer it once. A \"no\" with a reason still helps.",
  "ar": "كل توصية تم فحصها للمخزون والملاءمة. اعرضها مرة، الرفض مع السبب يفيد أيضاً."
 },
 "K_REASONS_T": {
  "en": "Add reasons the same day",
  "ar": "أضف الأسباب في نفس اليوم"
 },
 "K_REASONS": {
  "en": "Reasons take 5 seconds and help us stop sending the wrong products to your stores.",
  "ar": "الأسباب تأخذ ٥ ثوانٍ وتساعدنا على عدم إرسال منتجات غير مناسبة لمحلاتك."
 },
 "K_RETURN_T": {
  "en": "Keep first orders small",
  "ar": "اجعل الطلب الأول صغيراً"
 },
 "K_RETURN": {
  "en": "Start new products with one {unit}. Check sell-through before the second order.",
  "ar": "ابدأ المنتج الجديد بـ {unit} واحدة. تأكد من البيع قبل الطلب الثاني."
 },
 "K_PROMO_T": {
  "en": "Use the promo",
  "ar": "استخدم العرض"
 },
 "K_PROMO": {
  "en": "{promo} is live until {date}. Mention it first. It makes the order easy.",
  "ar": "{promo} ساري حتى {date}. اذكره أولاً، يسهّل الطلب."
 },
 "K_GOOD_T": {
  "en": "Keep it up",
  "ar": "استمر"
 },
 "K_GOOD": {
  "en": "Your upsells are up {pct}% on your usual level. Same approach next week.",
  "ar": "مبيعاتك الإضافية أعلى بـ {pct}٪ من مستواك المعتاد. نفس الأسلوب الأسبوع القادم."
 },
 "I_TAG_OVER": {
  "en": "Stores {tag} sell {ratio}× more {sku_group} than average",
  "ar": "المحلات {tag} تبيع {sku_group} أكثر بـ {ratio} ضعف من المتوسط"
 },
 "I_TAG_UNDER": {
  "en": "Stores {tag} sell {sku_group} {pct}% below average",
  "ar": "المحلات {tag} تبيع {sku_group} أقل بـ {pct}٪ من المتوسط"
 },
 "I_LABEL_OVER": {
  "en": "{label} stores take {ratio}× more {sku_group} per visit",
  "ar": "محلات {label} تأخذ {sku_group} أكثر بـ {ratio} ضعف في كل زيارة"
 },
 "I_SIZE_PACK": {
  "en": "{size} stores prefer {pack_type} ({pct}% of their {category} orders)",
  "ar": "محلات {size} تفضّل {pack_type} ({pct}٪ من طلبات {category})"
 },
 "I_TYPE_CONV": {
  "en": "{type} recommendations convert best: {pct}%",
  "ar": "توصيات {type} الأعلى نجاحاً: {pct}٪"
 },
 "I_FLAVOUR": {
  "en": "In {area}, {sku} outsells {sku2} {ratio} to 1",
  "ar": "في {area}، {sku} يتفوق على {sku2} بنسبة {ratio} إلى ١"
 },
 "M_UNREC": {
  "en": "{vsr} sold {sku} at {store}. Not recommended",
  "ar": "باع {vsr} {sku} في {store}، دون توصية"
 },
 "M_ALT": {
  "en": "Recommended {sku}, sold {alt} at {store}",
  "ar": "التوصية {sku}، والمباع {alt} في {store}"
 },
 "M_ACC": {
  "en": "{type}: {pct}% converted ({n} sent)",
  "ar": "{type}: نجاح {pct}٪ ({n} مُرسلة)"
 },
 "M_USEFUL": {
  "en": "Marked as training signal",
  "ar": "تم تحديده كإشارة تدريب"
 },
 "X_STORE_WELL": {
  "en": "Nothing to offer here today. This store is well stocked.",
  "ar": "لا شيء للعرض هنا اليوم، المحل مزوّد جيداً."
 },
 "X_STORE_GATED": {
  "en": "No recommendations. {gate}.",
  "ar": "لا توجد توصيات، {gate}."
 },
 "X_TODAY_NONE": {
  "en": "No stops planned today.",
  "ar": "لا توجد زيارات مخطط لها اليوم."
 },
 "X_TODO_DONE": {
  "en": "You're all caught up.",
  "ar": "لا يوجد شيء مطلوب منك الآن."
 },
 "X_FU_DONE": {
  "en": "All clear. Next check at {time}.",
  "ar": "لا توجد متابعات. التحديث القادم الساعة {time}."
 },
 "X_INBOX": {
  "en": "No notifications yet.",
  "ar": "لا توجد إشعارات بعد."
 },
 "X_FILTER": {
  "en": "No results for these filters.",
  "ar": "لا توجد نتائج لهذه الفلاتر."
 },
 "X_THREAD": {
  "en": "No messages yet. Start with a quick reply.",
  "ar": "لا توجد رسائل بعد. ابدأ برد سريع."
 },
 "X_PHOTOS": {
  "en": "No shelf photos yet.",
  "ar": "لا توجد صور رف بعد."
 },
 "X_LEARN": {
  "en": "No engine misses in this period.",
  "ar": "لا توجد أخطاء للنظام في هذه الفترة."
 },
 "X_TIPS": {
  "en": "No coaching tips yet.",
  "ar": "لا توجد نصائح بعد."
 },
 "O_V1": {
  "en": "Start here each morning: check today's recommendations and confirm.",
  "ar": "ابدأ من هنا كل صباح: راجع توصيات اليوم وأكّدها."
 },
 "O_V2": {
  "en": "When you reach a store, you'll get what to offer. Sell as usual in SalesBuzz.",
  "ar": "عند وصولك للمحل ستصلك المنتجات المقترحة. بِع كالمعتاد في SalesBuzz."
 },
 "O_V3": {
  "en": "If something doesn't sell, tell us why in two taps.",
  "ar": "إذا لم يُبَع منتج، وضّح السبب بضغطتين."
 },
 "O_S1": {
  "en": "Follow-ups show what needs you now. Each has one action.",
  "ar": "المتابعات تعرض ما يحتاجك الآن، ولكل منها إجراء واحد."
 },
 "O_S2": {
  "en": "Click any number or row to see the breakdown and act on it.",
  "ar": "اضغط على أي رقم أو صف لعرض التفاصيل واتخاذ الإجراء."
 },
 "O_S3": {
  "en": "Rules control what the system recommends. Nothing needs your approval.",
  "ar": "القواعد تتحكم فيما يوصي به النظام. لا شيء يحتاج موافقتك."
 },
 "O_NEXT": {
  "en": "Next",
  "ar": "التالي"
 },
 "O_DONE": {
  "en": "Got it",
  "ar": "فهمت"
 },
 "O_SKIP": {
  "en": "Skip tour",
  "ar": "تخطي الجولة"
 },
 "S_OFFLINE": {
  "en": "Offline. Your changes will sync",
  "ar": "غير متصل، ستتم مزامنة تغييراتك"
 },
 "S_SYNCED": {
  "en": "{n} changes synced",
  "ar": "تمت مزامنة {n} تغييرات"
 },
 "S_PENDING": {
  "en": "Waiting to sync",
  "ar": "بانتظار المزامنة"
 },
 "S_SB_DATA": {
  "en": "SalesBuzz data updated {time}",
  "ar": "تم تحديث بيانات SalesBuzz الساعة {time}"
 },
 "S_SB_OPENING": {
  "en": "Opening SalesBuzz… Place the order there. FieldDrive reads it automatically.",
  "ar": "جارٍ فتح SalesBuzz… سجّل الطلب هناك، وسيقرأه فيلد درايف تلقائياً."
 },
 "S_MAP_OFFLINE": {
  "en": "Map needs internet. Showing list",
  "ar": "الخريطة تحتاج إنترنت، يتم عرض القائمة"
 },
 "S_VAN_OFF": {
  "en": "Van stock not verified. SalesBuzz feed not connected",
  "ar": "مخزون السيارة غير مؤكد، لم يتم ربط SalesBuzz"
 },
 "S_SAVED": {
  "en": "Saved",
  "ar": "تم الحفظ"
 },
 "S_SENT": {
  "en": "Sent to {vsr}",
  "ar": "أُرسل إلى {vsr}"
 },
 "S_BLOCKED": {
  "en": "Blocked. {vsr} will no longer see it.",
  "ar": "تم الإيقاف. لن يظهر لـ {vsr} بعد الآن."
 },
 "S_PINNED": {
  "en": "Pinned until {date}",
  "ar": "مثبّت حتى {date}"
 },
 "S_EXEMPTED": {
  "en": "Marked as exempted",
  "ar": "تم الإعفاء"
 },
 "S_UNDO": {
  "en": "Undo",
  "ar": "تراجع"
 },
 "S_PHOTO_BIG": {
  "en": "Photo too large. Choose one under 5 MB",
  "ar": "الصورة كبيرة، اختر صورة أقل من ٥ ميغابايت"
 },
 "S_COMMENT_REQ": {
  "en": "Add a short comment for \"Other\"",
  "ar": "أضف تعليقاً قصيراً عند اختيار \"أخرى\""
 },
 "S_EXPORTED": {
  "en": "Export downloaded",
  "ar": "تم تنزيل الملف"
 },
 "Q_NET": {
  "en": "Net sales achievement",
  "ar": "تحقيق صافي المبيعات"
 },
 "Q_PVR": {
  "en": "Productive visits",
  "ar": "الزيارات المنتجة"
 },
 "Q_DROP": {
  "en": "Average order value",
  "ar": "متوسط قيمة الطلب"
 },
 "Q_XSELL": {
  "en": "Upsell quality",
  "ar": "جودة البيع الإضافي"
 },
 "Q_ACTION": {
  "en": "Recommendations acted on",
  "ar": "التوصيات المنفّذة"
 },
 "Q_RANK": {
  "en": "#{rank} of {n} · {move} this week",
  "ar": "المركز {rank} من {n} · {move} هذا الأسبوع"
 },
 "Q_CUE_NET": {
  "en": "Net sales are {pct}% under your usual. Start each visit with the top card.",
  "ar": "صافي مبيعاتك أقل بـ {pct}٪ من المعتاد. ابدأ كل زيارة بأول توصية."
 },
 "Q_CUE_PVR": {
  "en": "More visits are ending without an order. Offer at least one card at each stop.",
  "ar": "زيارات أكثر تنتهي بدون طلب. اعرض توصية واحدة على الأقل في كل زيارة."
 },
 "Q_CUE_DROP": {
  "en": "Orders are smaller than usual. Try the bigger pack where it sells steadily.",
  "ar": "الطلبات أصغر من المعتاد. جرّب العبوة الأكبر حيث يُباع المنتج بانتظام."
 },
 "Q_CUE_XSELL": {
  "en": "Upsells are being returned. Keep first orders to one {unit}.",
  "ar": "هناك مرتجعات في البيع الإضافي. اجعل الطلب الأول {unit} واحدة."
 },
 "Q_CUE_ACTION": {
  "en": "{n} recommendations have no reason yet. They take 5 seconds each.",
  "ar": "{n} توصيات بدون سبب. كل واحدة تأخذ ٥ ثوانٍ."
 },
 "Q_WEIGHTS": {
  "en": "Weights set by Americana",
  "ar": "الأوزان تحددها أمريكانا"
 },
 "R_T_RETURN": {
  "en": "Return pickup needed",
  "ar": "مطلوب استلام مرتجع"
 },
 "R_T_REQUEST": {
  "en": "Store request",
  "ar": "طلب من المحل"
 },
 "R_T_PRICE": {
  "en": "Price or promo question",
  "ar": "استفسار عن السعر أو العرض"
 },
 "R_T_ACCESS": {
  "en": "Access or timing issue",
  "ar": "مشكلة في الوصول أو التوقيت"
 },
 "R_T_OTHER": {
  "en": "Other",
  "ar": "أخرى"
 },
 "NF_FIT": {
  "en": "Didn't fit this store",
  "ar": "غير مناسب لهذا المحل"
 },
 "NF_TIME": {
  "en": "No time on this visit",
  "ar": "لم يتسع الوقت في هذه الزيارة"
 },
 "NF_BUSY": {
  "en": "Buyer busy",
  "ar": "المشتري مشغول"
 },
 "NF_OTHER": {
  "en": "Other (comment required)",
  "ar": "سبب آخر (التعليق مطلوب)"
 },
 "E_REVISIT": {
  "en": "Sold on revisit",
  "ar": "بيع في زيارة لاحقة"
 },
 "E_OPEN_NEXT": {
  "en": "Still open. Offer again on the next visit",
  "ar": "ما زالت مفتوحة، اعرضها في الزيارة القادمة"
 },
 "E_NOT_FOLLOWED": {
  "en": "Not followed",
  "ar": "لم يُتّبع"
 },
 "L_COL_CHECK2": {
  "en": "Confirmed after 28 days",
  "ar": "التأكيد بعد ٢٨ يوماً"
 },
 "K_CUSTOM": {
  "en": "{tip}",
  "ar": "{tip}"
 },
 "T_REVISIT": {
  "en": "Revisit {store}. {n} open recommendations",
  "ar": "زيارة {store} مرة أخرى، {n} توصيات مفتوحة"
 },
 "N_MSG": {
  "en": "{sup} wrote",
  "ar": "كتب {sup}"
 },
 "N_MSG_B": {
  "en": "{snippet}",
  "ar": "{snippet}"
 },
 "F_VSR_MSG": {
  "en": "{vsr} sent a message",
  "ar": "{vsr} أرسل رسالة"
 },
 "F_VSR_MSG_C": {
  "en": "\"{snippet}\"",
  "ar": "\"{snippet}\""
 },
 "F_PLAN_CHANGE": {
  "en": "{vsr} added a revisit to {store}",
  "ar": "{vsr} أضاف زيارة متكررة لمحل {store}"
 },
 "F_PLAN_CHANGE_C": {
  "en": "{date} · {reason}",
  "ar": "{date} · {reason}"
 },
 "F_ASSIGN_PENDING": {
  "en": "{store} moved to {vsr}",
  "ar": "نُقل محل {store} إلى {vsr}"
 },
 "F_ASSIGN_PENDING_C": {
  "en": "Pending SalesBuzz update",
  "ar": "بانتظار التحديث في SalesBuzz"
 }
});
})();
