(function () {
  // UI chrome labels (headers, tabs, buttons). Generated sentences live in the spec catalog; these are plain labels.
  const FD = globalThis.FD;
  const E = (en, ar) => ({ en, ar });
  Object.assign(FD.CATALOG, {
    L_COL_CARRIED: E('Products carried', 'المنتجات المتوفرة'), L_MORE: E('More', 'المزيد'),
    L_SEC_TEAM: E('How the team is doing', 'أداء الفريق'), L_SEC_ACT: E('Where to act next', 'أين تتصرف بعد ذلك'), L_SEC_SELLS: E('What is selling', 'ما الذي يُباع'),
    L_NO_VISITS_YET: E('No visits synced from SalesBuzz yet today', 'لا توجد زيارات مزامنة من SalesBuzz اليوم بعد'),
    L_WHAT_IS_THIS: E('What is this?', 'ما هذا؟'), L_COL_TREND: E('Trend', 'الاتجاه'),
    L_TREND_DAYS: E('Upsell value, last 8 selling days', 'قيمة البيع الإضافي، آخر ٨ أيام بيع'), L_TREND_WEEKS: E('Upsell value, last 8 weeks', 'قيمة البيع الإضافي، آخر ٨ أسابيع'),
    L_CMP_TODAY: E('Small figures compare with {date} up to {time}. Today is still in progress.', 'الأرقام الصغيرة تقارن بيوم {date} حتى الساعة {time}. اليوم لم ينتهِ بعد.'),
    L_STORE_TYPE: E('Store type', 'نوع المحل'), L_LOCATION_TYPE: E('Location type', 'نوع الموقع'),
    L_NEW_REASON: E('New reason', 'سبب جديد'), L_EDIT_REASON: E('Edit reason', 'تعديل السبب'), L_REASON_EN: E('Name in English', 'الاسم بالإنجليزية'), L_REASON_AR: E('Name in Arabic', 'الاسم بالعربية'),
    L_REASON_AR_HINT: E('Salesmen see the Arabic name. If you leave one empty, the other is used.', 'يرى المندوبون الاسم العربي. إذا تركت أحدهما فارغاً يُستخدم الآخر.'),
    L_HIDDEN: E('Hidden', 'مخفي'), L_SHOW: E('Show', 'إظهار'), L_HIDE: E('Hide', 'إخفاء'), L_DELETE: E('Delete', 'حذف'), L_CUSTOM: E('Custom', 'مخصص'), L_N_REASONS: E('{n} reasons', '{n} أسباب'),
    L_REASONS_NOTE: E('Salesmen pick from these when a recommendation is not sold. Past records keep their reason if you hide or delete one.', 'يختار المندوبون منها عند عدم بيع التوصية. السجلات السابقة تحتفظ بسببها عند الإخفاء أو الحذف.'),
    L_SHOW_ALL_N: E('Show all ({n})', 'عرض الكل ({n})'), L_SHOW_LESS: E('Show less', 'عرض أقل'),
    L_ON_HOLD_UNTIL: E('On hold until {date}: the store said no on {label}', 'موقوف حتى {date}: رفض المحل في {label}'), L_ALLOWED_AGAIN: E('Allowed again. It can be recommended on the next visit.', 'مسموح مجدداً. يمكن التوصية به في الزيارة القادمة.'),
    L_VIEW_LIST: E('View list', 'عرض القائمة'), L_HIDE_LIST: E('Hide list', 'إخفاء القائمة'), L_ASK_SUP_CHANGE: E('Ask supervisor to change', 'اطلب من المشرف التعديل'),
    L_TIP_MODE_TPL: E('Use a template', 'استخدم قالباً'), L_TIP_MODE_OWN: E('Write your own', 'اكتب بنفسك'),
    L_LOG_OUT: E('Log out', 'تسجيل الخروج'), L_SIGN_IN: E('Sign in', 'تسجيل الدخول'), L_SIGN_IN_AS: E('Sign in as', 'الدخول باسم'), L_SIGNED_OUT: E('You are signed out', 'تم تسجيل خروجك'),
    L_SETTINGS: E('Settings', 'الإعدادات'), L_EARLY_CHECK: E('Early: some sales are still in the 28-day check', 'مبكر: بعض المبيعات ما زالت ضمن فحص ٢٨ يوماً'),
    L_FOL_EXPL: E('Net sales change against before the pilot, for this salesman\'s stores that took recommendations compared with his other stores.', 'تغير صافي المبيعات مقارنة بما قبل التجربة، لمحلات المندوب التي أخذت التوصيات مقارنة بمحلاته الأخرى.'),
    I_FOLLOWUPS: E('Things that need you today, most important first. Each has one action. Done or dismissed items move to the Done tab.', 'أمور تحتاجك اليوم، الأهم أولاً. لكل منها إجراء واحد. ما تم أو تجاهلته ينتقل إلى تبويب المنجز.'),
    I_TEAM: E('Salesmen ranked by score (the weights are set in Rules). Small figures show the change against the comparison period. The trend line is upsell value.', 'ترتيب المندوبين حسب التقييم (الأوزان في القواعد). الأرقام الصغيرة تبين التغير مقارنة بفترة المقارنة. خط الاتجاه هو قيمة البيع الإضافي.'),
    I_WHY: E('Why recommended products were not sold, grouped by reason. Not followed means the salesman did not offer it.', 'أسباب عدم بيع المنتجات الموصى بها، مجمعة حسب السبب. لم يُتبع تعني أن المندوب لم يعرضه.'),
    I_OPPS: E('Products each store does not carry but similar stores sell, ranked by the margin the store could earn. Pin to push it, block to stop it.', 'منتجات لا يوفرها المحل بينما تبيعها محلات مشابهة، مرتبة حسب الهامش المتوقع للمحل. ثبّت للدفع بها أو أوقف لإيقافها.'),
    I_SKUS: E('How each product sells across your stores: how many carry it, how often it is taken when offered, and returns.', 'كيف يباع كل منتج في محلاتك: كم محلاً يوفره، ونسبة قبوله عند عرضه، والمرتجعات.'),
    I_ATTN: E('Stores with the lowest health score or a credit problem. Health combines range carried, freshness, ordering regularity and upsell uptake.', 'المحلات الأقل في درجة الصحة أو لديها مشكلة ائتمان. الصحة تجمع التشكيلة المتوفرة والطزاجة وانتظام الطلب وقبول البيع الإضافي.'),
    I_INSIGHTS: E('Patterns in what sells by area type, store class and pack size. Use them to choose what to push where.', 'أنماط ما يباع حسب نوع المنطقة وفئة المحل وحجم العبوة. استخدمها لاختيار ما تدفع به وأين.'),
    I_RULES: E('Numbers the system uses when it picks recommendations for each store every morning.', 'الأرقام التي يستخدمها النظام عند اختيار التوصيات لكل محل كل صباح.'),
    I_PINS: E('A pinned product is always recommended where it applies (a store, an area type or everywhere) until the end date, ahead of other picks. Store blocks and credit still apply.', 'المنتج المثبت يوصى به دائماً حيث ينطبق (محل أو نوع منطقة أو الكل) حتى تاريخ الانتهاء، قبل غيره. إيقاف المحل والائتمان ما زالا يطبقان.'),
    I_AREA: E('Products every store of this type or location is expected to carry. Missing ones become New for store recommendations.', 'منتجات يُتوقع أن يوفرها كل محل من هذا النوع أو الموقع. الناقص منها يصبح توصية جديدة للمحل.'),
    I_AUDIT: E('Every rule change, who made it and when.', 'كل تغيير على القواعد، ومن قام به ومتى.'),
    K_I_UPVAL: E('Cost value of upsold products that were ordered (full, partly or an alternative).', 'قيمة التكلفة للمنتجات الإضافية التي طُلبت (كاملة أو جزئياً أو بديل).'),
    K_I_NET: E('Sales minus returns for visited stores, compared with the average day before the pilot.', 'المبيعات ناقص المرتجعات للمحلات التي تمت زيارتها، مقارنة بمتوسط اليوم قبل التجربة.'),
    K_I_CONV: E('Share of offered recommendations that were sold.', 'نسبة التوصيات المعروضة التي بيعت.'),
    K_I_UPS: E('Recommendations sold. Reordered means the store ordered it again within 28 days.', 'التوصيات المباعة. أعيد طلبه يعني أن المحل طلبه مجدداً خلال ٢٨ يوماً.'),
    K_I_REASONS: E('Recommendations not sold or not offered that still have no reason from the salesman.', 'توصيات لم تُبع أو لم تُعرض وما زالت بدون سبب من المندوب.'),
    K_I_ATTN: E('Stores with low health or a credit problem.', 'محلات بصحة منخفضة أو لديها مشكلة ائتمان.'),
    L_MINIMISE: E('Minimise', 'تصغير'), L_ALL_STORES_F: E('All stores', 'كل المحلات'), L_ALL_TOPICS: E('All topics', 'كل المواضيع'), L_HAS_FILES: E('With attachments', 'مع مرفقات'),
    L_SHOWING: E('Showing', 'المعروض'), L_CLEAR_ALL: E('Clear all', 'مسح الكل'), L_FILTER_STORE: E('Show only this store', 'عرض هذا المحل فقط'),
    L_TAG_NOTE: E('Messages are tagged with the store you are at, so your supervisor sees where they came from.', 'تُربط الرسائل بالمحل الذي أنت فيه، ليعرف المشرف من أين جاءت.'),
    L_TODAY_PLAN: E("Today's plan", 'خطة اليوم'), L_SUP_CHANGED: E('Changed by supervisor', 'عدّله المشرف'), L_CHANGED_BY_YOU: E('Changed by you', 'عدّلته أنت'), L_ADDED_BY_YOU: E('Added by you', 'أضفته أنت'),
    L_REMOVED: E('Removed', 'أزيل'), L_RESTORE: E('Restore', 'استعادة'), L_ADD_PRODUCT: E('Add product', 'إضافة منتج'), L_ADD_STORE_VISIT: E('Add store visit', 'إضافة زيارة محل'), L_REMOVE_STOP: E('Remove stop', 'إزالة المحطة'),
    L_CHANGE_REC: E('Change recommendation', 'تعديل التوصية'), L_PLAN_CONFIRMED: E('Confirmed by the salesman', 'أكدها المندوب'), L_PLAN_NOT_CONFIRMED: E('Not confirmed by the salesman yet', 'لم يؤكدها المندوب بعد'),
    L_PLAN_NOTE: E('Changes go to the salesman straight away with a notification.', 'تصل التعديلات للمندوب فوراً مع إشعار.'), L_PLAN_STOPS: E('{n} stops', '{n} محطات'), L_NO_PLAN_TODAY: E('No selling today', 'لا توجد مبيعات اليوم'),
    L_CARRIED_HERE: E('carried here', 'متوفر هنا'),
    L_WHOLE_TEAM: E('Whole team', 'كل الفريق'), L_TEAM_SUB: E('Group · {n} salesmen', 'مجموعة · {n} مندوبين'), L_NEW_MSGS: E('New messages', 'رسائل جديدة'), L_YESTERDAY: E('Yesterday', 'أمس'),
    L_OPEN_FULL: E('Open full chat', 'فتح المحادثة كاملة'), L_EARLIER: E('{n} earlier messages. Open full chat', '{n} رسائل سابقة. افتح المحادثة كاملة'), L_ATTACH: E('Attach', 'إرفاق'), L_ATTACHMENT: E('Attachment', 'مرفق'),
    L_FILE_BIG: E('{label} is over 2 MB and was not added', '{label} أكبر من ٢ ميجابايت ولم يُرفق'), L_FILES_MAX: E('Up to {n} files per message', 'حتى {n} ملفات في الرسالة'), L_FILE_GONE: E('File not available on this device', 'الملف غير متوفر على هذا الجهاز'),
    L_REPLYING: E('Replying to {label}', 'رد على {label}'), L_SEARCH_CHAT: E('Search in conversation', 'بحث في المحادثة'), L_SEARCH_CHATS: E('Search conversations', 'بحث في المحادثات'), L_N_MATCHES: E('{n} found', '{n} نتيجة'),
    L_SEEN: E('Seen', 'تمت القراءة'), L_SENT: E('Sent', 'تم الإرسال'), L_CHOOSE_CHAT: E('Choose a conversation', 'اختر محادثة'), L_YOU: E('You', 'أنت'),
    L_F_ALL: E('All', 'الكل'), L_F_UNREAD: E('Unread', 'غير مقروءة'), L_F_STORES: E('Stores', 'المحلات'), L_F_VSRS: E('Salesmen', 'المندوبون'),
    QV_OK: E('Okay, will do', 'تمام، سأفعل'), QV_DONE: E('Done, the owner agreed', 'تم، وافق صاحب المحل'), QV_LATER: E('Will try on the next visit', 'سأحاول في الزيارة القادمة'), QV_CALL: E('Can you call me?', 'هل يمكنك الاتصال بي؟'),
    L_PTS: E('pts', 'نقطة'), L_NEW_SINCE_PILOT: E('New in pilot', 'جديد مع التجربة'), L_COL_NET_VS: E('Net sales vs before pilot', 'صافي المبيعات مقارنة بما قبل التجربة'),
    L_CMP_NOTE: E('Small figures show the change against {date} to {label}.', 'الأرقام الصغيرة تبين التغير مقارنة بالفترة من {date} إلى {label}.'),
    L_CMP_NOTE_PRE: E('Small figures compare with {date} to {label}, before the pilot. Upsell figures start with the pilot.', 'الأرقام الصغيرة تقارن بالفترة من {date} إلى {label} قبل التجربة. أرقام البيع الإضافي تبدأ مع التجربة.'),
    L_FILTERS: E('Filters', 'الفلاتر'), L_REORDER_DUE: E('Reorder due', 'حان وقت الطلب'), L_LIKELY_NEEDS: E('Likely needs a regular reorder today: {label}', 'يحتاج على الأغلب طلباً عادياً اليوم: {label}'),
    L_COVER_HELP: E('Est. days left: the last delivery divided by what the store buys per day on average (4 weeks), minus the days since. Shelf stock is not counted.', 'الأيام المتبقية تقديرياً: آخر توريد مقسوماً على متوسط شراء المحل اليومي (٤ أسابيع) ناقص الأيام منذ التوريد. لا يتم عد مخزون الرف.'),
    CR_OK: E('OK', 'سليم'), CR_WATCH: E('On watch', 'تحت المراقبة'), CR_BLOCKED: E('Blocked', 'موقوف'),
    CRL_OK: E('Credit OK', 'الائتمان سليم'), CRL_WATCH: E('Credit on watch', 'الائتمان تحت المراقبة'), CRL_BLOCKED: E('Credit blocked', 'الائتمان موقوف'),
    L_WATCH_BEFORE: E('Returns, 28 days before', 'المرتجعات، ٢٨ يوماً قبل'), L_WATCH_SINCE: E('Returns since added', 'المرتجعات منذ الإضافة'), L_WATCH_HELD: E('Stores held back today', 'محلات بدون توصية اليوم'),
    L_WATCH_NOTE: E('On the watchlist since {date}. Not recommended while watched. Regular orders continue.', 'في قائمة المراقبة منذ {date}. لا تتم التوصية به أثناء المراقبة. الطلبات العادية مستمرة.'),
    L_WATCH_SETTLED: E('Returns are counted against the sale date. Sales from the last 12 days are left out while their returns come in.', 'تحسب المرتجعات حسب تاريخ البيع. مبيعات آخر ١٢ يوماً غير محسوبة حتى تكتمل مرتجعاتها.'),
    L_WATCH_DAY: E('Day {days} of {n}', 'اليوم {days} من {n}'), L_WATCH_REVIEW_ON: E('Review on {date}', 'المراجعة في {date}'),
    L_WATCH_IMPROVED: E('Returns improved', 'تحسنت المرتجعات'), L_WATCH_NOT_IMPROVED: E('Returns not improved', 'لم تتحسن المرتجعات'),
    L_WATCH_KEEP: E('Keep watching 2 more weeks', 'استمر في المراقبة أسبوعين'), L_WATCH_PAST: E('Past watchlist periods', 'فترات مراقبة سابقة'), L_TO: E('to', 'إلى'),
    L_WATCH_HOW: E('Watched products are not recommended. After 2 weeks you get a follow-up comparing returns before and since.', 'المنتجات المراقبة لا يتم التوصية بها. بعد أسبوعين تصلك متابعة تقارن المرتجعات قبل وبعد.'),
    L_BLOCKED: E('Blocked', 'موقوف'), L_BLOCKED_HERE_T: E('Blocked at this store', 'موقوف في هذا المحل'), L_BLOCKED_ALL_T: E('Blocked everywhere', 'موقوف في كل المحلات'),
    L_BLOCKED_IN_N: E('Blocked in {n} stores', 'موقوف في {n} محلات'), L_ALL_PRODUCTS: E('All products', 'كل المنتجات'), L_ONE_REC: E('One recommendation', 'توصية واحدة'),
    L_COL_WHERE: E('Where', 'أين'), L_COL_SINCE: E('Since', 'منذ'),
    L_BLOCKS_NOTE: E('Blocked products are not recommended until you unblock them.', 'المنتجات الموقوفة لا يتم التوصية بها حتى تلغي الإيقاف.'),
    L_SEC_RECS: E('What gets recommended', 'ما يتم التوصية به'), L_SEC_SCORE: E('How salesmen are scored', 'كيف يتم تقييم المندوبين'), L_SEC_HISTORY: E('History', 'السجل'), L_OPEN_SHORT: E('Still open', 'مفتوحة'), SK_OFFPLAN: E('Off-plan visit', 'زيارة خارج الخطة'),
    L_MY_STORES: E('My stores', 'محلاتي'), L_ON_PLAN_TODAY: E('On today’s plan', 'ضمن خطة اليوم'), L_OTHER_STORES: E('Other assigned stores', 'محلات أخرى مخصصة لك'),
    L_NOT_ON_PLAN: E('Not on today’s plan', 'ليس ضمن خطة اليوم'), L_ADD_VISIT_TODAY: E('Add visit today', 'إضافة زيارة اليوم'), L_OFF_PLAN_NOTE: E('Adding this visit is recorded as an off-plan visit.', 'تُسجل هذه الزيارة كزيارة خارج الخطة.'),
    L_SEARCH_STORES: E('Search my stores', 'ابحث في محلاتي'), L_WHAT_HAPPENED: E('What happened', 'ماذا حدث'), L_STILL_PENDING: E('Still pending', 'ما زال معلقاً'), L_ACTIONS_TAKEN: E('Actions taken', 'الإجراءات المتخذة'),
    L_FU_OPEN: E('Open', 'مفتوحة'), L_FU_DONE: E('Done', 'منتهية'), FU_UNDO: E('Reopened', 'أعيد فتحها'), DONE: E('Done', 'تم'), L_NOTHING_PENDING: E('Nothing pending.', 'لا يوجد شيء معلق.'),
    L_PENDING_N: E('{n} still pending', '{n} ما زالت معلقة'), L_DONE_VIA: E('{status} · {date} {time}', '{status} · {date} {time}'),
    L_SCORECARD_SETUP: E('Scorecard', 'بطاقة الأداء'), L_COL_IN_SCORE: E('In score', 'ضمن التقييم'), L_COL_WEIGHT: E('Weight', 'الوزن'), L_COL_SEES: E('Salesman sees', 'يظهر للمندوب'), L_EXPAND: E('Open full page', 'فتح الصفحة كاملة'), L_PIN_NAV: E('Keep menu open', 'تثبيت القائمة'), L_UNPIN_NAV: E('Collapse menu', 'طي القائمة'),
    L_WHY_NOT_FOLLOWED: E('Why wasn\u2019t it offered?', 'لماذا لم تُعرض؟'), L_GENERAL: E('General', 'عام'), L_STORE_THREADS: E('Store conversations', 'محادثات المحلات'), L_NEW_MSG: E('New message', 'رسالة جديدة'), L_MESSAGE: E('Message', 'مراسلة'),
    L_VISIT_AGAIN: E('Visit again', 'زيارة مرة أخرى'), L_LATER_TODAY: E('Later today', 'لاحقاً اليوم'), L_NEXT_VISIT_DAY: E('Next visit day', 'يوم الزيارة التالي'), L_REVISIT: E('Revisit', 'زيارة متكررة'),
    L_CARRIED_FROM: E('Open since {date} · {reason}', 'مفتوحة منذ {date} · {reason}'), L_STORE_PRODUCTS: E('Products at this store', 'المنتجات في هذا المحل'),
    L_SKU_STATS: E('Last {date} · {qty} · {n} in 4 weeks', 'آخر طلب {date} · {qty} · {n} خلال ٤ أسابيع'), L_COVER_DAYS: E('~{days} days cover', '~{days} أيام تغطية'), L_ADD_PHOTOS: E('Add shelf photos', 'إضافة صور للرف'),
    L_COL_UNITS_4W: E('Units, 4 weeks', 'الوحدات، ٤ أسابيع'), L_COL_AVG_VISIT: E('Avg per visit', 'المتوسط لكل زيارة'), L_COL_COVER: E('Est. days left', 'الأيام المتبقية تقديرياً'), L_FROM_SB: E('From SalesBuzz orders (what we sold in). Shelf stock is not counted.', 'من طلبات SalesBuzz (ما بعناه للمحل). لا يتم عد مخزون الرف.'),
    L_TIMELINE: E('Timeline', 'السجل الزمني'), L_VISIT: E('Visit', 'زيارة'), L_ORDER_LINE: E('Order · {n} products · {money}', 'طلب · {n} منتجات · {money}'),
    L_VISIT_ORDER_SAME: E('Visit + order {date}', 'زيارة وطلب {date}'), L_VISIT_ON: E('Visit {date}', 'زيارة {date}'), L_ORDER_ON: E('Order {date}', 'طلب {date}'), L_COL_VISIT_ORDER: E('Last visit / order', 'آخر زيارة / طلب'),
    L_REC_RESPONSE: E('How this store responds to recommendations', 'تجاوب المحل مع التوصيات'), L_REC_RESPONSE_STORES: E('Response by store', 'التجاوب حسب المحل'), L_RESPONSE: E('Response', 'التجاوب'),
    L_RESPONSE_NOTE: E('Based on what this store ordered after each recommendation.', 'بناءً على طلبات المحل بعد كل توصية.'), L_NOT_FOLLOWED_PCT: E('Not followed', 'لم تُتّبع'),
    SEG_RECEPTIVE: E('Receptive', 'متجاوب'), SEG_SELECTIVE: E('Selective', 'انتقائي'), SEG_RESISTANT: E('Resistant', 'غير متجاوب'), SEG_NEW: E('Not enough data', 'بيانات غير كافية'),
    L_REASSIGN: E('Change salesman', 'تغيير المندوب'), L_CHANGE_ROUTE: E('Change route', 'تغيير المسار'), L_PENDING_SB: E('Pending SalesBuzz update', 'بانتظار التحديث في SalesBuzz'),
    L_ASSIGN_NOTE: E('Applies from the next planned day. SalesBuzz owns journey plans, so this also needs updating there.', 'يُطبق من يوم الخطة التالي. خطط المسار في SalesBuzz، لذا يلزم تحديثها هناك أيضاً.'),
    L_METRIC_OFF: E('Off', 'متوقف'), L_VSR_SEES: E('What salesmen see', 'ما يظهر للمندوبين'), L_VSR_SEES_D: E('Tap to hide or show on the salesman\u2019s scorecard.', 'اضغط للإخفاء أو الإظهار في تقييم المندوب.'), L_SEE_RANK: E('Rank', 'الترتيب'),
    L_AREA_ASSORT: E('Area assortment', 'تشكيلة المناطق'), L_AREA_ASSORT_D: E('Worked out from what sells in each area type and store class; drives new-product recommendations.', 'محسوبة مما يُباع في كل نوع منطقة وفئة محل؛ وتوجه توصيات المنتجات الجديدة.'), L_RECALC: E('Recalculate from sales', 'إعادة الحساب من المبيعات'),
    L_TIP_CUSTOM: E('Write your own', 'اكتب نصيحتك'), L_TIP_TITLE: E('Title', 'العنوان'), L_TIP_BODY: E('Message', 'الرسالة'), L_INTERNAL: E('Internal page for the analytics team. Not shown to supervisors.', 'صفحة داخلية لفريق التحليل. لا تظهر للمشرفين.'),
    L_KPI_OF_OFFERED: E('{n} of {qty} offered', '{n} من {qty} عُرضت'), AU_ASSIGN: E('Salesman assignment changed', 'تم تغيير تعيين المندوب'), AU_WEIGHTS: E('Scorecard weights changed', 'تم تعديل أوزان التقييم'), L_W_TOTAL: E('Total {pct}%', 'الإجمالي {pct}٪'), L_W_NOTE: E('Draft weights. Scores are scaled to the total. Final weights set with Americana.', 'أوزان مبدئية. يتم تعديل التقييم حسب الإجمالي. الأوزان النهائية تحدد مع أمريكانا.'), L_RESET: E('Reset', 'إعادة الضبط'), L_NOTE: E('Note', 'ملاحظة'), L_PILOT: E('Pilot', 'التجربة'), L_TOPIC: E('Topic', 'الموضوع'), L_RECS_N: E('{n} to offer', '{n} للعرض'), L_ACTIONS: E('Actions', 'الإجراءات'),
    L_PITCH_COST: E('Store pays', 'يدفع المحل'), L_PITCH_SELLS: E('Sells for', 'يبيع بـ'), L_PITCH_EARN: E('Store earns', 'ربح المحل'), L_BACK: E('Back', 'رجوع'), L_CLOSE: E('Close', 'إغلاق'), L_OPEN: E('Open', 'فتح'), L_DONE: E('Done', 'تم'), L_CONFIRM: E('Confirm', 'تأكيد'), L_EDIT: E('Edit', 'تعديل'),
    L_ADD: E('Add', 'إضافة'), L_REMOVE: E('Remove', 'إزالة'), L_SEND: E('Send', 'إرسال'), L_ACCEPT: E('Accept', 'قبول'), L_REJECT: E('Reject', 'رفض'), L_ALL: E('All', 'الكل'),
    L_OPTIONAL: E('Optional', 'اختياري'), L_CHANGE: E('Change', 'تغيير'), L_NONE_YET: E('None yet', 'لا يوجد بعد'), L_IGNORE: E('Ignore', 'تجاهل'), L_NOW: E('Now', 'الآن'),
    L_ALL_ROUTES: E('All routes', 'كل المسارات'), L_P_TODAY: E('Today', 'اليوم'), L_P_WEEK: E('This week', 'هذا الأسبوع'), L_P_PILOT: E('Pilot to date', 'منذ بداية التجربة'), L_P_CUSTOM: E('Custom', 'مخصص'),
    L_FROM: E('From', 'من'), L_TO: E('To', 'إلى'), L_SEARCH_PH: E('Search stores, products or salesmen', 'ابحث عن محل أو منتج أو مندوب'), L_ROUTE: E('Route', 'المسار'),
    L_KPI_UPSELLS: E('Upsells sold', 'مبيعات إضافية'), L_KPI_FOOT_UPS: E('{n} upsells · {pct}% of offers', '{n} بيع إضافي · {pct}٪ من العروض'), L_KPI_TARGET: E('{pct}% of target', '{pct}٪ من الهدف'),
    L_KPI_OF_SENT: E('{n} of {qty} recommendations', '{n} من {qty} توصية'), L_KPI_UPS_FOOT: E('{n} reordered · {qty} awaiting 28-day check', '{n} أعيد طلبها · {qty} بانتظار فحص ٢٨ يوماً'), L_KPI_MISSING_BY: E('Mostly {vsr}', 'غالباً {vsr}'), L_KPI_STORES_OF: E('of {n} stores', 'من {n} محل'),
    L_COL_RANK: E('#', '#'), L_COL_VSR: E('Salesman', 'المندوب'), L_COL_SCORE: E('Score', 'التقييم'), L_COL_NET: E('Net sales', 'صافي المبيعات'), L_COL_UPVAL: E('Upsell value', 'قيمة البيع الإضافي'),
    L_COL_UPS: E('Upsells', 'البيع الإضافي'), L_COL_CONV: E('Conversion', 'نسبة النجاح'), L_COL_CHANGE: E('vs before', 'مقارنة بالسابق'), L_COL_FOLLOWED: E('Offered', 'نسبة العرض'),
    L_COL_FOL_CHG: E('Stores taking recommendations', 'المحلات التي تأخذ التوصيات'), L_COL_REASONS: E('Reasons given', 'الأسباب المسجلة'), L_COL_PVR: E('Productive visits', 'الزيارات المنتجة'), L_COL_DROP: E('Avg order', 'متوسط الطلب'),
    L_COL_XSELL: E('Upsell quality', 'جودة البيع الإضافي'), L_COL_ACTION: E('Recommendations acted on', 'التوصيات المنفذة'), L_COL_RETURNS: E('Returns', 'المرتجعات'), L_COL_TREND: E('Last weeks', 'آخر الأسابيع'),
    L_COL_STORE: E('Store', 'المحل'), L_COL_PRODUCT: E('Product', 'المنتج'), L_COL_TYPE: E('Type', 'النوع'), L_COL_QTY: E('Qty', 'الكمية'), L_COL_CODE: E('Code', 'الرمز'), L_COL_DATE: E('Date', 'التاريخ'),
    L_COL_CARRYING: E('Stores carrying', 'المحلات الموفرة'), L_COL_SALES: E('Sales', 'المبيعات'), L_COL_ATTEMPTS: E('Offered', 'مرات العرض'), L_COL_SUSTAINED: E('Reordered', 'أعيد طلبه'),
    L_COL_PROMO: E('Promo', 'العرض'), L_COL_HEALTH: E('Health', 'الصحة'), L_COL_LABEL: E('Class', 'الفئة'), L_COL_SIZE: E('Size', 'الحجم'), L_COL_TAGS: E('Area', 'المنطقة'),
    L_COL_GAPS: E('Missing', 'ناقص'), L_COL_LAST: E('Last order', 'آخر طلب'), L_COL_CREDIT: E('Credit', 'الائتمان'), L_COL_OUTCOME: E('Outcome', 'النتيجة'), L_COL_REASON: E('Reason', 'السبب'),
    L_COL_CHECK: E('28-day check', 'فحص ٢٨ يوماً'), L_COL_ID: E('ID', 'الرقم'), L_COL_SKIPPED: E('Stop', 'الزيارة'),
    L_OPEN_TEAM: E('Open team', 'عرض الفريق'), L_OPEN_OPPS: E('All opportunities', 'كل الفرص'), L_OPEN_SKUS: E('All products', 'كل المنتجات'), L_OPEN_STORES: E('All stores', 'كل المحلات'),
    L_BAND_GOOD: E('Healthy', 'جيد'), L_BAND_WATCH: E('Watch', 'مراقبة'), L_BAND_LOW: E('Needs attention', 'يحتاج متابعة'),
    L_H_COVERAGE: E('Range coverage', 'تغطية التشكيلة'), L_H_FRESH: E('Freshness', 'الطزاجة'), L_H_CONSIST: E('Consistency', 'الانتظام'), L_H_UPTAKE: E('Upsell uptake', 'تقبل البيع الإضافي'),
    SH_CARRIED: E('Carried', 'متوفر'), SH_PENDING: E('Pending check', 'قيد التأكيد'), SH_OPPORTUNITY: E('Opportunity', 'فرصة'), SH_LAPSED: E('Lapsed', 'انقطع'),
    SH_DECLINED: E('Declined', 'مرفوض'), SH_GATED: E('Not eligible', 'غير مؤهل'), SH_RETURNED: E('Returned', 'مرتجع'), SH_NONE: E('Not stocked', 'غير متوفر'),
    L_OVERVIEW: E('Overview', 'نظرة عامة'), L_HISTORY: E('History', 'السجل'), L_ORDERS: E('Orders', 'الطلبات'), L_RECS: E('Recommendations', 'التوصيات'), L_PHOTOS: E('Photos', 'الصور'),
    L_STAGES: E('Recommendation journey', 'مراحل التوصية'), L_BLOCK_REC: E('Block this recommendation', 'إيقاف هذه التوصية'), L_OVERRIDE_CD: E('Allow again now', 'السماح بإعادة العرض'),
    L_UNEXEMPT: E('Remove exemption', 'إلغاء الإعفاء'), L_EXEMPT_NOTE: E('Why is it exempt? (optional)', 'سبب الإعفاء (اختياري)'), L_REASON: E('Reason', 'السبب'), L_COMMENT: E('Comment', 'التعليق'),
    L_PHOTO: E('Photo', 'الصورة'), L_OUTCOME: E('Outcome', 'النتيجة'), L_QTY_SUGGESTED: E('Suggested', 'المقترح'), L_QTY_CHANGED: E('Changed to', 'عُدلت إلى'),
    ST_GEN: E('Generated', 'أُنشئت'), ST_SENT: E('Sent', 'أُرسلت'), ST_VIEWED: E('Viewed', 'شوهدت'), ST_OFFERED: E('Offered', 'عُرضت'), ST_OUTCOME: E('Outcome', 'النتيجة'), ST_MATURITY: E('Confirmed after 28 days', 'التأكيد بعد ٢٨ يوماً'),
    L_R_NUMBERS: E('Recommendation rules', 'قواعد التوصية'), L_R_LAPSED: E('Treat as lapsed after (days)', 'اعتبار الطلب منقطعاً بعد (أيام)'), L_R_COOLDOWN: E('Wait after a no (days)', 'الانتظار بعد الرفض (أيام)'),
    L_R_MATURITY: E('Confirm an upsell after (days)', 'تأكيد البيع الإضافي بعد (أيام)'), L_R_MAX: E('Most recommendations per store', 'أقصى عدد توصيات لكل محل'), L_R_FIRST: E('First order limit (units)', 'حد الطلب الأول (وحدات)'),
    L_R_BLOCKS: E('Blocked', 'الموقوفة'), L_R_PINS: E('Pinned', 'المثبتة'), L_R_MUST: E('Must-stock lists', 'قوائم المنتجات الأساسية'), L_R_WATCH: E('Returns watchlist', 'قائمة مراقبة المرتجعات'),
    L_R_VANFEED: E('Van stock from SalesBuzz', 'مخزون السيارة من SalesBuzz'), L_R_VANFEED_D: E('Off: cards say van stock is not verified and the van check is hidden.', 'عند الإيقاف: تظهر البطاقات بدون تأكيد مخزون السيارة ويُخفى فحص الحمولة.'),
    L_R_WEIGHTS: E('Scorecard weights', 'أوزان التقييم'), L_R_CODES: E('Reason codes', 'رموز الأسباب'), L_R_AUDIT: E('Change log', 'سجل التغييرات'),
    L_CHANGED_BY: E('{sup} · {date} {time}', '{sup} · {date} {time}'), L_EVERYWHERE: E('All stores', 'كل المحلات'), L_SCOPE: E('Where', 'النطاق'), L_UNTIL: E('Until', 'حتى'),
    L_PRODUCT: E('Product', 'المنتج'), L_STORE: E('Store', 'المحل'), L_BLOCK_STORE: E('Stop recommendations here', 'إيقاف التوصيات لهذا المحل'), L_BLOCK_SKU_HERE: E('Block product here', 'إيقاف المنتج هنا'),
    L_BLOCK_EVERY: E('Block everywhere', 'إيقاف في كل المحلات'), L_PIN_HERE: E('Pin here', 'تثبيت هنا'), L_PIN_TAG: E('Pin for an area type', 'تثبيت لنوع منطقة'), L_WATCH_ADD: E('Add to watchlist', 'إضافة لقائمة المراقبة'),
    L_WATCH_REMOVE: E('Remove from watchlist', 'إزالة من قائمة المراقبة'), L_BLOCK_STORE_Q: E('Stop all recommendations for {store}?', 'إيقاف كل التوصيات لمحل {store}؟'), L_UNBLOCK: E('Unblock', 'إلغاء الإيقاف'),
    L_SCOPE_ALL: E('Everywhere', 'في كل مكان'), L_SCOPE_TAG: E('Area type', 'نوع المنطقة'), L_SCOPE_LABEL: E('Store class', 'فئة المحل'), L_SCOPE_ROUTE: E('Route', 'المسار'), L_SCOPE_STORE: E('One store', 'محل واحد'),
    AU_BLOCK: E('Block added', 'تمت إضافة إيقاف'), AU_UNBLOCK: E('Block removed', 'تمت إزالة إيقاف'), AU_PIN: E('Pin added', 'تمت إضافة تثبيت'), AU_UNPIN: E('Pin removed', 'تمت إزالة تثبيت'),
    AU_WATCH: E('Added to watchlist', 'أضيف لقائمة المراقبة'), AU_UNWATCH: E('Removed from watchlist', 'أزيل من قائمة المراقبة'), AU_RULE: E('Rule changed', 'تم تعديل قاعدة'), AU_VANFEED: E('Van stock setting changed', 'تم تغيير إعداد مخزون السيارة'), AU_STORE: E('Store details edited', 'تم تعديل بيانات المحل'),
    L_MISSES: E('Engine misses', 'أخطاء النظام'), L_ACCURACY: E('How each recommendation type converts', 'نجاح كل نوع من التوصيات'), L_EXPORT: E('Export training events (CSV)', 'تصدير بيانات التدريب (CSV)'),
    L_MARK_USEFUL: E('Use for training', 'استخدام للتدريب'), L_MISS_UNREC: E('Sold without recommendation', 'بيع دون توصية'), L_MISS_ALT: E('Sold alternative', 'بيع بديل'), L_MISSES_D: E('Sales the engine did not predict. Each one teaches the next model.', 'مبيعات لم يتوقعها النظام. كل حالة تحسّن النموذج القادم.'),
    L_LIST: E('List', 'قائمة'), L_GRID: E('Grid', 'شبكة'), L_ALL_TAGS: E('All areas', 'كل المناطق'), L_ALL_LABELS: E('All classes', 'كل الفئات'), L_ALL_CATS: E('All categories', 'كل الأصناف'),
    L_ALL_VSRS: E('All salesmen', 'كل المندوبين'), L_ALL_SIZES: E('All sizes', 'كل الأحجام'), L_ALL_BANDS: E('All health', 'كل الحالات'), L_ALL_STATES: E('All states', 'كل الحالات'),
    L_BY_VSR: E('By salesman', 'حسب المندوب'), L_BY_STORE: E('By store', 'حسب المحل'), L_BY_SKU: E('By product', 'حسب المنتج'), L_BY_LABEL: E('By class', 'حسب الفئة'), L_BY_TAG: E('By area', 'حسب المنطقة'), L_BY_SIZE: E('By size', 'حسب الحجم'),
    L_DAILY_NET: E('Daily net sales', 'صافي المبيعات اليومي'), L_BASE_AVG: E('Before-pilot average', 'متوسط ما قبل التجربة'), L_REASON_MIX: E('Why recommendations did not sell', 'أسباب عدم بيع التوصيات'),
    L_SKIPS: E('Skipped or moved stops', 'الزيارات المتجاوزة أو المؤجلة'), L_TIPS_SENT: E('Tips sent', 'النصائح المرسلة'), L_VIEW_ROUTE: E('View route map', 'عرض خريطة المسار'), L_SCORECARD: E('Scorecard', 'بطاقة الأداء'),
    L_TEMPLATE: E('Tip', 'النصيحة'), L_EDIT_TEXT: E('Wording', 'النص'), L_TO_VSR: E('To', 'إلى'), L_WHERE_SELLS: E('Where it sells (pieces per store per week)', 'أين يُباع (قطع لكل محل أسبوعياً)'),
    L_DECLINES: E('Why it was declined', 'أسباب الرفض'), L_OPEN_OPP_STORES: E('Stores with an open opportunity', 'محلات بفرصة مفتوحة'), L_PROMO_UPTAKE: E('Promo uptake', 'الاستفادة من العرض'),
    L_STORES_MISSING: E('Stores in this group without it', 'محلات في هذه المجموعة لا توفره'), L_WATCHLIST_FLAG: E('On watchlist', 'ضمن المراقبة'), L_PCS_WEEK: E('pcs / store / week', 'قطعة / محل / أسبوع'),
    L_GOOD_MORNING: E('Good morning, {vsr}', 'صباح الخير يا {vsr}'), L_GOOD_DAY: E('Hello, {vsr}', 'مرحباً يا {vsr}'), L_PROGRESS: E('{n} of {qty} stops · {got} upsells', '{n} من {qty} زيارات · {got} بيع إضافي'),
    L_REVIEWED: E('List confirmed · {n} products', 'تم تأكيد القائمة · {n} منتجات'), L_STORES_N: E('{n} stores', '{n} محلات'), L_STORES_1: E('1 store', 'محل واحد'), L_NEED_ON_VAN: E('Need {n} · on van {qty}', 'المطلوب {n} · في السيارة {qty}'),
    L_VAN_SHORT: E('{n} recommendations will show as not on van', '{n} توصيات ستظهر غير متوفرة في السيارة'), L_VAN_OK: E('Van has everything for today', 'السيارة فيها كل المطلوب اليوم'),
    L_SKIP_STOP: E('Skip stop', 'تجاوز الزيارة'), L_MOVE_LATER: E('Move to end', 'تأجيل للأخير'), L_CALL: E('Call store', 'اتصال بالمحل'), L_UNDO_SKIP: E('Undo skip', 'إلغاء التجاوز'),
    L_MAP: E('Map', 'خريطة'), L_YOU_ARE_HERE: E('You are here', 'موقعك'), L_OFFER: E('Offer', 'العرض'), L_PROFILE: E('Profile', 'الملف'), L_QTY: E('Quantity', 'الكمية'),
    L_BACK_FD: E('Back to FieldDrive', 'العودة إلى فيلد درايف'), L_LAST_VISIT: E('Last order {date}', 'آخر طلب {date}'), L_NEXT_STOP: E('Next stop', 'الزيارة التالية'), L_NO_RECS: E('No recommendations', 'لا توجد توصيات'),
    L_WHY_SELL: E("Why didn't it sell?", 'لماذا لم يُبع؟'), L_WHY_OFFER: E('Why not offered?', 'لماذا لم يُعرض؟'), L_WHICH_BRAND: E('Which brand?', 'أي علامة؟'), L_REASON_IS: E('Reason: {reason}', 'السبب: {reason}'),
    L_SUGGEST_FIX: E('Suggest a correction', 'اقترح تصحيحاً'), L_LAST_8: E('Recent orders', 'الطلبات الأخيرة'), L_TODO_REASONS: E('Reasons needed', 'أسباب مطلوبة'), L_TODO_TIPS: E('Coaching tips', 'نصائح'),
    L_TODO_REPLIES: E('Replies', 'الردود'), L_TODO_CORR: E('Corrections', 'التصحيحات'), L_MY_SCORE: E('My scorecard', 'تقييمي'), L_MY_UPSELLS: E('My upsells', 'مبيعاتي الإضافية'),
    L_TIPS_RECEIVED: E('Tips from your supervisor', 'نصائح المشرف'), L_SETTINGS: E('Settings', 'الإعدادات'), L_LANGUAGE: E('Language', 'اللغة'), L_DIGITS: E('Numbers', 'الأرقام'),
    L_DIGITS_AR: E('Arabic ١٢٣', 'عربية ١٢٣'), L_DIGITS_LAT: E('Latin 123', 'لاتينية 123'), L_TEXT_SIZE: E('Text size', 'حجم الخط'), L_NORMAL: E('Normal', 'عادي'), L_LARGE: E('Large', 'كبير'),
    L_THEME: E('Appearance', 'المظهر'), L_AUTO: E('Auto', 'تلقائي'), L_LIGHT: E('Light', 'فاتح'), L_DARK: E('Dark', 'داكن'), L_REPLAY_TOUR: E('Replay tour', 'إعادة الجولة'), L_HELP: E('Help', 'مساعدة'),
    L_INBOX: E('Notifications', 'الإشعارات'), L_MARK_ALL: E('Mark all read', 'تحديد الكل كمقروء'), L_VS_USUAL: E('vs your usual', 'مقارنة بمعدلك'), L_TYPE_MSG: E('Write a message', 'اكتب رسالة'),
    L_QUICK: E('Quick replies', 'ردود سريعة'), L_YESTERDAY: E('Yesterday', 'أمس'), L_MOVE_UP: E('up {n}', 'تقدم {n}'), L_MOVE_DOWN: E('down {n}', 'تراجع {n}'), L_MOVE_SAME: E('no change', 'بدون تغيير'),
    L_FILTER_PENDING: E('Pending', 'قيد التأكيد'), L_FILTER_SUSTAINED: E('Reordered', 'أعيد طلبه'), L_FILTER_RETURNED: E('Returned', 'مرتجع'), L_TOTAL: E('Total', 'الإجمالي'),
    L_UPSELL_VALUE_YOU: E('Upsell value this pilot', 'قيمة مبيعاتك الإضافية'), L_SUPERVISOR: E('Supervisor', 'المشرف'), L_RIYADH_TT: E('Riyadh traditional trade', 'تجارة التجزئة التقليدية - الرياض'),
    L_PILOT_DAY: E('Pilot day {n} of 90', 'اليوم {n} من ٩٠ للتجربة'), L_TODAY_STOPS: E('{n} stops today', '{n} زيارات اليوم'), L_REMOTE: E('Remote route', 'مسار بعيد'),
    L_CUSTOM_RANGE: E('Choose dates', 'اختر التواريخ'), L_APPLY: E('Apply', 'تطبيق'), L_STATUS_ARRIVED: E('At store', 'في المحل'), L_STATUS_PLANNED: E('Planned', 'مخطط'),
    L_STATUS_DONE: E('Done', 'تمت'), L_STATUS_SKIPPED: E('Skipped', 'متجاوزة'), L_STATUS_MOVED: E('Moved', 'مؤجلة'), L_ON_VAN_SHORT: E('Not on van', 'غير متوفر'),
    L_PIN_UNTIL_VISIT: E('Pinned for the next visit', 'مثبّت للزيارة القادمة'), L_WHY: E('Why', 'السبب'), L_STOCK: E('Stock', 'المخزون'),
    L_BLOCKED_STORE: E('Recommendations stopped for this store', 'التوصيات متوقفة لهذا المحل'), L_CHOOSE: E('Choose', 'اختر'), L_PREV_OUTCOME: E('Was: {status}', 'كان: {status}'),
    L_UNREAD: E('Unread', 'غير مقروء'), L_FOLLOWUPS_ALL: E('All follow-ups', 'كل المتابعات'), L_TIP_DRAFTS: E('Suggested tips', 'نصائح مقترحة'), L_EXEMPTED_BY: E('Exempted: {snippet}', 'معفى: {snippet}'),
    L_VAN_FEED_NOTE: E('Needs the SalesBuzz van-stock feed', 'يتطلب ربط مخزون السيارة من SalesBuzz'), L_OFFER_ALL_DONE: E('All recommendations handled here', 'تم التعامل مع كل التوصيات هنا'),
  });
})();
